b2b:
  sbc:
    xfer:
      blind_immediate_release: no
      enable: no
kamailio:
  proxy:
    lnp:
      api:
        keepalive_interval: 3
        port: 8991
        request_timeout: 1000
        server: localhost
      enable: yes
      type: local
    skip_cf_loop: 'yes'
    allow_refer_method: no
    generate_responder_cdr_data: no
pbx:
  enable: no
