kamailio:
  proxy:
    lnp:
      api:
        keepalive_interval: 3
        port: 8991
        request_timeout: 1000
        server: localhost
      enable: yes
      type: local
    skip_cf_loop: 'yes'
